#Mapping properties
#Thu Mar 14 13:57:28 CET 2024
mapping.input.max.depth=-1
mapping.input.element=EventData
mapping.db.id=not applicable
mapping.input.exist=true
mapping.output.max.depth=-1
mapping.db.location=not applicable
mapping.output.element=JariItemExport_Data
mapping.output.exist=true
