#Mapping properties
#Thu Mar 07 09:31:01 CET 2024
mapping.input.max.depth=-1
mapping.input.element=EventData
mapping.db.id=-1
mapping.input.exist=true
mapping.output.max.depth=-1
mapping.db.location=n/a(imported from mapping unit)
mapping.output.element=n/a
mapping.output.exist=false
